### ISSUE TITLE
Missing important functions

### ISSUE THREAD

**Issue by ot-repo** [iminsoftware/imin_printer#1]
Hello,

we are a software company from Germany which produces a POS System. As hardware we sell our customers iMin devices with integrated printers.
We have the following problem: After some time the printer stops working. This problem does not occur in every device and totally unexpected. 

Beforehand we have written our own flutter plugin to be able to use the iMin printer SDK. Now we have seen that you have built one. We want to use it but we have realised that two important functions are missing:

1. Future<bool> printRawData(Uint8List data) which takes a list of POS commands a byte array and send them to the printer.
2. Future<bool> openCashBox() which opens the cash box.

Is that possible that you add those two methods for us?

Thank you!

**Comment by pkasidit** [comment]
+1

Thanks
